# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-12 14:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_confirm.models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default=django_confirm.models.default_key, max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField(default=django_confirm.models.default_expires)),
                ('purpose', models.CharField(blank=True, max_length=16, null=True)),
                ('payload', jsonfield.fields.JSONField(default=django_confirm.models.default_payload)),
            ],
        ),
    ]
